    pip install spacy==2.3.5

    pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz

    pip install pyresparser

In [2]:
from pyresparser import ResumeParser

In [3]:
data = ResumeParser("CV.pdf").get_extracted_data()

C:\Users\vito pm\anaconda3\envs\test\lib\site-packages\spacy\util.py:275: UserWarning: [W031] Model 'en_training' (0.0.0) requires spaCy v2.1 and is incompatible with the current spaCy version (2.3.5). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)

In [5]:

data

{'name': 'Kalash Jindal',
 'email': 'jindalkalash298@gmail.com',
 'mobile_number': '7839453651',
 'skills': ['Database',
  'Coding',
  'Design',
  'Chemicals',
  'Python',
  'Programming',
  'Modeling',
  'Computer science',
  'Training',
  'Statistics',
  'Api',
  'Pyqt',
  'Github',
  'C',
  'Testing',
  'C++',
  'Html',
  'Keras',
  'Ui',
  'Analysis',
  'Prototype',
  'Opencv',
  'Css',
  'Algorithms',
  'Engineering',
  'Word',
  'Sci'],
 'college_name': None,
 'degree': None,
 'designation': None,
 'experience': None,
 'company_names': None,
 'no_of_pages': 3,
 'total_experience': 0}

In [10]:
import pandas as pd

df = pd.DataFrame.from_dict(data)
df

,name,email,mobile_number,skills,college_name,degree,designation,experience,company_names,no_of_pages,total_experience
0,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Database,None,None,None,None,None,3,0
1,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Coding,None,None,None,None,None,3,0
2,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Design,None,None,None,None,None,3,0
3,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Chemicals,None,None,None,None,None,3,0
4,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Python,None,None,None,None,None,3,0
5,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Programming,None,None,None,None,None,3,0
6,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Modeling,None,None,None,None,None,3,0
7,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Computer science,None,None,None,None,None,3,0
8,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Training,None,None,None,None,None,3,0
9,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Statistics,None,None,None,None,None,3,0
10,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Api,None,None,None,None,None,3,0
11,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Pyqt,None,None,None,None,None,3,0
12,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Github,None,None,None,None,None,3,0
13,Kalash Jindal,jindalkalash298@gmail.com,7839453651,C,None,None,None,None,None,3,0
14,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Testing,None,None,None,None,None,3,0
15,Kalash Jindal,jindalkalash298@gmail.com,7839453651,C++,None,None,None,None,None,3,0
16,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Html,None,None,None,None,None,3,0
17,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Keras,None,None,None,None,None,3,0
18,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Ui,None,None,None,None,None,3,0
19,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Analysis,None,None,None,None,None,3,0
20,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Prototype,None,None,None,None,None,3,0
21,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Opencv,None,None,None,None,None,3,0
22,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Css,None,None,None,None,None,3,0
23,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Algorithms,None,None,None,None,None,3,0
24,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Engineering,None,None,None,None,None,3,0
25,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Word,None,None,None,None,None,3,0
26,Kalash Jindal,jindalkalash298@gmail.com,7839453651,Sci,None,None,None,None,None,3,0